package org.henrygucker.logispim.fileprocessor.actionlisteners;

import org.henrygucker.logimips.fileprocessor.backend.*;
import org.henrygucker.logispim.fileprocessor.backend.MIPSCrossCompiler;
import org.henrygucker.logispim.fileprocessor.backend.PlatformToolchainCommands;
import org.henrygucker.logispim.fileprocessor.backend.SettingsManager;
import org.henrygucker.logispim.fileprocessor.backend.elf.ElfFile;
import org.henrygucker.logispim.fileprocessor.backend.elf.ElfFormatException;
import org.henrygucker.logispim.fileprocessor.backend.elf.SectionHeader;
import org.henrygucker.logispim.fileprocessor.backend.elf.Symbol;
import org.henrygucker.logispim.fileprocessor.backend.exceptions.CompilationException;
import org.henrygucker.logispim.fileprocessor.backend.exceptions.SettingsManagerException;
import org.henrygucker.logispim.fileprocessor.App;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class CompileActionListener implements ActionListener {

    private final App app;

    private static Thread worker = null;

    public CompileActionListener(App app) {
        this.app = app;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (this.worker != null && this.worker.isAlive())
            // Ignores compile button press if the worker thread has not completed
            return;

        // Use of worker thread to allow for GUI to remain responsive
        Thread worker = new Thread(this::performAction);
        worker.start();
    }

    private synchronized void performAction() {
        // Getting settings values for compilation
        Path outputDir = null;
        Path sourcePath = null;
        Boolean isKernelText = null;
        try {
            outputDir = (Path) app.getSetting(SettingsManager.Settings.OUTPUT_DIRECTORY_ABSOLUTE_PATH);
            sourcePath = (Path) app.getSetting(SettingsManager.Settings.SOURCE_FILE_ABSOLUTE_PATH);
            isKernelText = (Boolean) app.getSetting(SettingsManager.Settings.IS_KERNEL_TEXT);
        } catch (SettingsManagerException e) {
            app.errorMessage(e.getTitle(), e.getIsolatedMessage());
        }

        // Checking validity of read values

        // Invalid if was unable to get path (null returned) or if path is not directed at a directory
        if (outputDir == null || !outputDir.toFile().exists() || !outputDir.toFile().isDirectory()) {
            app.errorMessage("Compilation Error", "Invalid output directory selected.");
            return;
        }

        // Invalid if was unable to get source path (null returned)
        if (sourcePath == null) {
            app.errorMessage("Compilation Error", "Invalid source path selected.");
            return;
        }

        // Invalid if source file does not exist
        if (!sourcePath.toFile().exists()) {
            app.errorMessage("Compilation Error", "Invalid source path selected. No file at \"" + sourcePath.toString() + "\" exists.");
            return;
        }

        // Invalid if source "file" is a directory
        if (sourcePath.toFile().isDirectory()) {
            app.errorMessage("Compilation Error", "Invalid source path selected. \"" + sourcePath.toString() + "\" is a directly, not a file.");
            return;
        }

        // Invalid if issue reading true/false value (null returned)
        if (isKernelText == null) {
            app.errorMessage("Compilation Error", "An error occurred while reading settings for compilation. Try again.");

            return;
        }

        Path elfPath = generateElfFile(sourcePath, outputDir, isKernelText);

        // Issue occurred in generateElfFile(), and action exits. Notification was generated by generateElfFile()
        if (elfPath == null)
            return;

        ElfFile elfFile = null;
        try {
            elfFile = new ElfFile(elfPath);
        } catch (IOException e) {
           app.errorMessage("Compilation Error", "An error occurred while reading compiled ELF file. Try again.");
           return;
        } catch (ElfFormatException e) {
            app.errorMessage("Compilation Error", e.getMessage());
            return;
        }


        String sourceName = sourcePath.getFileName().toString().split("\\.")[0];

        // elfPath is located in /outputDir/sourceName/bin/sourceName.elf
        // elfPath.getParent().getParent() is then /outputDir/sourceName
        Path binarySectionDataOutputDir = elfPath.getParent().getParent();
        Path textOutputFile = binarySectionDataOutputDir.resolve("text.hex");
        Path dataOutputFile = binarySectionDataOutputDir.resolve("data.hex");
        Path kernelTextOutputFile = binarySectionDataOutputDir.resolve("text-kernel.hex");

        Path[] outputFilePaths = new Path[]{
                textOutputFile,
                dataOutputFile,
                kernelTextOutputFile
        };

        // Purges old output files to not confuse users if compilation fails or if program with same name is compiled as
        // non-kernel text, and then is compiled as kernel text.
        for (int i = 0; i < outputFilePaths.length; i++) {
            try {
                deleteRecursive(outputFilePaths[i]);
            } catch (IOException e) {
                app.errorMessage(
                        "Compilation Error",
                        "An IO issue occurred while deleting contents occupying output location \"" +
                        outputFilePaths[i].toAbsolutePath().toString() + "\". Try again."
                );
                return;
            } catch (SecurityException e) {
                app.errorMessage(
                        "Compilation Error",
                        "This process lacks permission to delete contents occupying output location \"" +
                                outputFilePaths[i].toAbsolutePath().toString() + "\"."
                );
            }
        }

        // Writing appropriate
        if (isKernelText) {
            writeKernelTextBinaryFiles(elfFile, kernelTextOutputFile);
        } else {
            writeNonKernelTextBinaryFiles(elfFile, textOutputFile, dataOutputFile);
        }

        ArrayList<String> objdumpArgs = new ArrayList<>();
        for (String arg : PlatformToolchainCommands.getAppropriateCommands().getObjdumpCommand())
            objdumpArgs.add(arg);

        objdumpArgs.add("-D");

        objdumpArgs.add(PlatformToolchainCommands.pathToAppropriateString(elfPath));

        ProcessBuilder pb = new ProcessBuilder(objdumpArgs);
        Process objdump = null;
        try {
            objdump = pb.start();
        } catch (IOException e) {
            app.updateTextArea("An IO error occurred when fetching instructions.\nTry again.");
            return;
        }

        // Only stores lines in data and text sections
        boolean shouldStoreLines = false;
        StringBuilder objdumpOutputBuilder = new StringBuilder();
        try (BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(objdump.getInputStream()))) {
            String line;
            while ((line = bufferedReader.readLine()) != null) {
                if (line.equals("Disassembly of section .text:"))
                    shouldStoreLines = true;
                else if (line.equals("Disassembly of section .data:"))
                    shouldStoreLines = true;
                else if (line.startsWith("Disassembly of section "))
                    shouldStoreLines = false;
                
                if (shouldStoreLines) {
                    objdumpOutputBuilder.append(line);
                    objdumpOutputBuilder.append('\n');
                }
            }
        } catch (IOException e) {
            app.updateTextArea(
                    "Error when fetching instructions.\n" +
                    "An issue occurred with IO."
            );
            return;
        }

        try {
            objdump.waitFor(15, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
            app.updateTextArea(
                    "Error when fetching instructions.\n" +
                    "Worker thread interrupted."
            );
            return;
        }

        if (objdump.isAlive()) {
            objdump.destroy();

            app.updateTextArea(
                    "Error when fetching instructions.\n" +
                    "Runtime limit exceeded."
            );
            return;
        }

        app.updateTextArea(objdumpOutputBuilder.toString());

        JOptionPane.showMessageDialog(
                app,
                "Output files can be found in \"" + binarySectionDataOutputDir.toString() + "\".",
                "Compilation Complete",
                JOptionPane.PLAIN_MESSAGE
        );
    }

    private void writeKernelTextBinaryFiles(ElfFile elfFile, Path kernelTextBinaryFile) {
        ByteBuffer currSectionContent = null;

        // Fetching text section content
        try {
            currSectionContent = elfFile.getSectionContent(".text");
        } catch (IOException e) {
            app.errorMessage("Compilation Error", "An error occurred while reading compiled ELF file. Try again.");
            return;
        } catch (ElfFormatException | IllegalArgumentException e) {
            app.errorMessage("Compilation Error", "Unable to locate .text section in compiled input file.");
            return;
        }

        // Needs to overwrite words at following symbols with these big-endian values as little-endian values:
        // - exit: 0x50000000
        // - print_char: 0x54000000
        HashMap<String, Integer> symbolOffsets = new HashMap<>();
        HashMap<String, Integer> symbolReplacements = new HashMap<>();
        symbolReplacements.put("exit", 0x50000000);
        symbolReplacements.put("print_char", 0x54000000);

        // Gets start of text section (should always be 0x80000000, but checks to make sure)
        int textSectionStart = 0x80000000;
        for (SectionHeader sh : elfFile.sectionHeaders)
            if (elfFile.getSectionName(sh).equals(".text")) {
                textSectionStart = sh.addr();
                break;
            }

        // Gets offsets of symbols with names as keys in symbolReplacements and stores in symbolOffsets
        for (Symbol sym : elfFile.symbols) {
            symbolOffsets.put(elfFile.getSymbolName(sym), sym.value() - textSectionStart);
        }

        // Replaces words at symbol locations in ByteBuffer
        for (String symbolName : symbolOffsets.keySet()) {
            if (!symbolReplacements.containsKey(symbolName))
                continue;

            currSectionContent.putInt(symbolOffsets.get(symbolName), symbolReplacements.get(symbolName));
        }

        try {
            writeBufferToLogisimHexFile(currSectionContent, kernelTextBinaryFile);
        } catch (IOException e) {
            app.errorMessage("Compilation Error", "An error occurred while writing \"text-kernel\" binary file.");
        }

        return;
    }

    private void writeNonKernelTextBinaryFiles(ElfFile elfFile, Path textBinaryFile, Path dataBinaryFile) {
        ByteBuffer currSectionContent = null;

        // Fetching text section content
        try {
            currSectionContent = elfFile.getSectionContent(".text");
        } catch (IOException e) {
            app.errorMessage("Compilation Error", "An error occurred while reading compiled ELF file. Try again.");
            return;
        } catch (ElfFormatException | IllegalArgumentException e) {
            app.errorMessage("Compilation Error", "Unable to locate .text section in compiled input file.");
            return;
        }

        // File writing for non-kernel text
        try {
            writeBufferToLogisimHexFile(currSectionContent, textBinaryFile);
        } catch (IOException e) {
            app.errorMessage("Compilation Error", "An error occurred while writing \"text\" binary file.");
        }

        // Fetching data section content
        try {
            currSectionContent = elfFile.getSectionContent(".data");
        } catch (IOException e) {
            app.errorMessage("Compilation Error", "An error occurred while reading compiled ELF file. Try again.");
            return;
        } catch (ElfFormatException | IllegalArgumentException e) {
            app.errorMessage("Compilation Error", "Unable to locate .data section in compiled input file.");
            return;
        }

        // Writing data content to file
        try {
            writeBufferToLogisimHexFile(currSectionContent, dataBinaryFile);
        } catch (IOException e) {
            app.errorMessage("Compilation Error", "An error occurred while writing \"data\" binary file.");
        }

    }

    /**
     * Generates ELF file from source MIPS assembly file following the given parameters.
     * @param sourcePath {@link Path} to source MIPS assembly file.
     * @param outputDir {@link Path} to home output directory.
     * @param isKernelText {@code true} if compiling kernel instructions, otherwise {@code false}.
     * @return {@link Path} to generated ELF file.
     */
    private Path generateElfFile(Path sourcePath, Path outputDir, boolean isKernelText) {
        Path linkerScriptPath = null;
        try {
            linkerScriptPath = getLinkerscriptPath(isKernelText);
        } catch (IOException e) {
            app.errorMessage("Compilation Error", "An error occurred while generating linker script.");

            return null;
        }

        MIPSCrossCompiler crossCompiler = new MIPSCrossCompiler(sourcePath, linkerScriptPath, outputDir, isKernelText);
        String sourceName = sourcePath.getFileName().toString().split("\\.")[0];
        Path preProcessedSourcePath = outputDir.resolve(sourceName + File.separator + "bin" + File.separator + sourceName + "_processed.s");
        Path elfPath = null;
        try {
            elfPath = crossCompiler.compile();
        } catch (CompilationException e) {
            app.updateTextAreaWithFileContent(preProcessedSourcePath);
            app.errorMessage(e.getTitle(), e.getIsolatedMessage());
        } catch (IOException | InterruptedException e) {
            app.errorMessage("Compilation Error", "An error occurred during the back-end compilation process. Try again.");
        }

        return elfPath;
    }

    /**
     * Writes appropriate linker script to local file to be read by linker.
     * @param isKernelText {@code true} if the user is compiling kernel instructions, otherwise {@code false}.
     * @return {@link Path} to appropriate linker script
     */
    private Path getLinkerscriptPath(boolean isKernelText) throws IOException {
        Path outPath = app.getHomePath().resolve("linkerscripts");
        Files.createDirectories(outPath);

        // Determining destination file name
        if (isKernelText) {
            outPath = outPath.resolve("linkerscript_kernel_text.ld");
        } else {
            outPath = outPath.resolve("linkerscript.ld");
        }

        // Name of resource file to read in resources directory of source code
        String linkerscriptResourceName = "linkerscript.ld";
        if (isKernelText)
            linkerscriptResourceName = "linkerscript-kernel-text.ld";

        byte[] inn = new byte[1024];
        int numRead = 0;
        try (
                BufferedOutputStream writer = new BufferedOutputStream(new FileOutputStream(outPath.toFile()));
                InputStream inputStream = ClassLoader.getSystemResourceAsStream(linkerscriptResourceName)
        ) {
            // Writing the first numRead bytes from inn after reading numRead bytes from file until no bytes are left to read
            while ((numRead = inputStream.readNBytes(inn, 0, 1024)) != 0) {
                writer.write(inn, 0, numRead);
            }
        }

        return outPath;
    }

    /**
     * Writes the remaining content of a ByteBuffer to a file at the specified path following hex byte format for Logisim-Evolution.
     * @param byteBuffer Source of data to write.
     * @param file Destination file location.
     * @throws IOException If an issue with IO occurs.
     */
    private static void writeBufferToLogisimHexFile(ByteBuffer byteBuffer, Path file) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file.toFile()))) {
            writer.write("v3.0 hex bytes\n");
            while (byteBuffer.hasRemaining()) {
                writer.write(String.format("%02x ", Byte.toUnsignedInt(byteBuffer.get())));
            }
        }
    }

    /**
     * Deletes file/directory at a specified path recursively.
     * @param path The {@link Path} to the file/directory that will be deleted. Will do nothing if no file exists at this {@link Path}.
     * @throws IOException If an IO issue occurs.
     * @throws SecurityException Thrown by the security manager to indicate a lack of permission to delete a file.
     */
    private static void deleteRecursive(Path path) throws IOException, SecurityException {
        // Skip if non-existent path
        if (!path.toFile().exists())
            return;

        // Deletes file at path
        if (!path.toFile().isDirectory()) {
            Files.delete(path);
            return;
        }

        // Deletes contents of directory
        List<Path> childrenPaths;
        try (Stream<Path> entries = Files.list(path)) {
            childrenPaths = entries.collect(Collectors.toUnmodifiableList());

            for (Path child : childrenPaths) {
                deleteRecursive(child);
            }
        } finally {
            Files.delete(path);
        }
    }
}
