name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '22' # Specify your Java version
        distribution: 'temurin'
        cache: maven # Built-in caching for Maven dependencies
    - name: Install Xvfb
      run: |
          sudo apt-get update
          sudo apt-get install -y xvfb # Install Xvfb

    - name: Build and run tests
      run: xvfb-run --auto-servernum mvn -X --batch-mode test